/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PrivateWeatherGuessInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getEncryptedConfidence"
      | "getEncryptedTemperature"
      | "getLeaderboardCount"
      | "getLeaderboardEntry"
      | "getPrediction"
      | "getPredictionCount"
      | "getUserPredictionCount"
      | "getUserPredictions"
      | "leaderboard"
      | "leaderboardIds"
      | "owner"
      | "pause"
      | "paused"
      | "predictionCount"
      | "predictions"
      | "protocolId"
      | "revealPrediction"
      | "submitPrediction"
      | "transferOwnership"
      | "unpause"
      | "updateLeaderboardAccuracy"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LeaderboardUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "PredictionRevealed"
      | "PredictionSubmitted"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getEncryptedConfidence",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedTemperature",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLeaderboardCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLeaderboardEntry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrediction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPredictionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPredictionCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPredictions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "leaderboard",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "leaderboardIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "predictionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "predictions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revealPrediction",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitPrediction",
    values: [string, BigNumberish, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateLeaderboardAccuracy",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getEncryptedConfidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedTemperature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLeaderboardCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLeaderboardEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPrediction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPredictionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPredictionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPredictions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "leaderboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "leaderboardIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "predictionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "predictions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revealPrediction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitPrediction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateLeaderboardAccuracy",
    data: BytesLike
  ): Result;
}

export namespace LeaderboardUpdatedEvent {
  export type InputTuple = [predictionId: BigNumberish, accuracy: BigNumberish];
  export type OutputTuple = [predictionId: bigint, accuracy: bigint];
  export interface OutputObject {
    predictionId: bigint;
    accuracy: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PredictionRevealedEvent {
  export type InputTuple = [
    predictionId: BigNumberish,
    predictor: AddressLike,
    actualTemperature: BigNumberish,
    accuracy: BigNumberish
  ];
  export type OutputTuple = [
    predictionId: bigint,
    predictor: string,
    actualTemperature: bigint,
    accuracy: bigint
  ];
  export interface OutputObject {
    predictionId: bigint;
    predictor: string;
    actualTemperature: bigint;
    accuracy: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PredictionSubmittedEvent {
  export type InputTuple = [
    predictionId: BigNumberish,
    predictor: AddressLike,
    location: string,
    targetDate: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    predictionId: bigint,
    predictor: string,
    location: string,
    targetDate: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    predictionId: bigint;
    predictor: string;
    location: string;
    targetDate: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivateWeatherGuess extends BaseContract {
  connect(runner?: ContractRunner | null): PrivateWeatherGuess;
  waitForDeployment(): Promise<this>;

  interface: PrivateWeatherGuessInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getEncryptedConfidence: TypedContractMethod<
    [predictionId: BigNumberish],
    [string],
    "view"
  >;

  getEncryptedTemperature: TypedContractMethod<
    [predictionId: BigNumberish],
    [string],
    "view"
  >;

  getLeaderboardCount: TypedContractMethod<[], [bigint], "view">;

  getLeaderboardEntry: TypedContractMethod<
    [predictionId: BigNumberish],
    [
      [string, bigint, bigint] & {
        predictor: string;
        actualTemperature: bigint;
        accuracy: bigint;
      }
    ],
    "view"
  >;

  getPrediction: TypedContractMethod<
    [predictionId: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, boolean] & {
        predictor: string;
        location: string;
        targetDate: bigint;
        submissionTime: bigint;
        isRevealed: boolean;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getPredictionCount: TypedContractMethod<[], [bigint], "view">;

  getUserPredictionCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getUserPredictions: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  leaderboard: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        predictor: string;
        actualTemperature: bigint;
        predictionId: bigint;
        accuracy: bigint;
      }
    ],
    "view"
  >;

  leaderboardIds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  predictionCount: TypedContractMethod<[], [bigint], "view">;

  predictions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, boolean] & {
        predictor: string;
        location: string;
        targetDate: bigint;
        submissionTime: bigint;
        isRevealed: boolean;
        isActive: boolean;
      }
    ],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  revealPrediction: TypedContractMethod<
    [predictionId: BigNumberish, actualTemperature: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitPrediction: TypedContractMethod<
    [
      location: string,
      targetDate: BigNumberish,
      encryptedTemperature: BytesLike,
      temperatureProof: BytesLike,
      encryptedConfidence: BytesLike,
      confidenceProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateLeaderboardAccuracy: TypedContractMethod<
    [predictionId: BigNumberish, accuracy: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getEncryptedConfidence"
  ): TypedContractMethod<[predictionId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedTemperature"
  ): TypedContractMethod<[predictionId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getLeaderboardCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLeaderboardEntry"
  ): TypedContractMethod<
    [predictionId: BigNumberish],
    [
      [string, bigint, bigint] & {
        predictor: string;
        actualTemperature: bigint;
        accuracy: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPrediction"
  ): TypedContractMethod<
    [predictionId: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, boolean] & {
        predictor: string;
        location: string;
        targetDate: bigint;
        submissionTime: bigint;
        isRevealed: boolean;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPredictionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserPredictionCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserPredictions"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "leaderboard"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        predictor: string;
        actualTemperature: bigint;
        predictionId: bigint;
        accuracy: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "leaderboardIds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "predictionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "predictions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, boolean] & {
        predictor: string;
        location: string;
        targetDate: bigint;
        submissionTime: bigint;
        isRevealed: boolean;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revealPrediction"
  ): TypedContractMethod<
    [predictionId: BigNumberish, actualTemperature: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitPrediction"
  ): TypedContractMethod<
    [
      location: string,
      targetDate: BigNumberish,
      encryptedTemperature: BytesLike,
      temperatureProof: BytesLike,
      encryptedConfidence: BytesLike,
      confidenceProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateLeaderboardAccuracy"
  ): TypedContractMethod<
    [predictionId: BigNumberish, accuracy: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "LeaderboardUpdated"
  ): TypedContractEvent<
    LeaderboardUpdatedEvent.InputTuple,
    LeaderboardUpdatedEvent.OutputTuple,
    LeaderboardUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PredictionRevealed"
  ): TypedContractEvent<
    PredictionRevealedEvent.InputTuple,
    PredictionRevealedEvent.OutputTuple,
    PredictionRevealedEvent.OutputObject
  >;
  getEvent(
    key: "PredictionSubmitted"
  ): TypedContractEvent<
    PredictionSubmittedEvent.InputTuple,
    PredictionSubmittedEvent.OutputTuple,
    PredictionSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "LeaderboardUpdated(uint256,uint256)": TypedContractEvent<
      LeaderboardUpdatedEvent.InputTuple,
      LeaderboardUpdatedEvent.OutputTuple,
      LeaderboardUpdatedEvent.OutputObject
    >;
    LeaderboardUpdated: TypedContractEvent<
      LeaderboardUpdatedEvent.InputTuple,
      LeaderboardUpdatedEvent.OutputTuple,
      LeaderboardUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PredictionRevealed(uint256,address,int256,uint256)": TypedContractEvent<
      PredictionRevealedEvent.InputTuple,
      PredictionRevealedEvent.OutputTuple,
      PredictionRevealedEvent.OutputObject
    >;
    PredictionRevealed: TypedContractEvent<
      PredictionRevealedEvent.InputTuple,
      PredictionRevealedEvent.OutputTuple,
      PredictionRevealedEvent.OutputObject
    >;

    "PredictionSubmitted(uint256,address,string,uint256,uint256)": TypedContractEvent<
      PredictionSubmittedEvent.InputTuple,
      PredictionSubmittedEvent.OutputTuple,
      PredictionSubmittedEvent.OutputObject
    >;
    PredictionSubmitted: TypedContractEvent<
      PredictionSubmittedEvent.InputTuple,
      PredictionSubmittedEvent.OutputTuple,
      PredictionSubmittedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
